version: "3.9"

services:
  mysql_database:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./src/db:/docker-entrypoint-initdb.d
      - skills-test-mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
    restart: always

volumes:
  skills-test-mysql:
